In [1]:
# Importar a Biblioteca
import pandas as pd

#### **IMPORTANDO A PLANILHA E OBSERVANDO POSSÍVEIS DADOS QUE SERÃO TRATADOS**

In [2]:
# Abrir a planilha pelo pandas e criar um DataFrame
df = pd.read_csv(
    "vendas_projeto_auditor.csv",
    sep=",",
    encoding="utf-8-sig"
)

print("Planilha csv importada com sucesso!")

print("\nExibir 5 primeiras linhas")
display(df.head())


print(f"\nA quantidade de linhas e colunas respectivamente é: {df.shape}")

Planilha csv importada com sucesso!

Exibir 5 primeiras linhas

   id_venda        data  produto  quantidade  preco_unitario forma_pagamento
0     10322  2026-01-01   Camisa         6.0            59.9             Pix
1     10088  2026-01-02    Tênis         3.0           239.9         Crédito
2     10397  2026-01-02   Camisa         6.0            59.9             Pix
3     10414  2026-01-02    Short         6.0            79.9        Dinheiro
4     10033  2026-01-03  Chinelo         4.0            49.9         Crédito

A quantidade de linhas e colunas respectivamente é: (1015, 6)

#### **VERIFICAR A QUANTIDADE DE LINHAS VAZIAS POR COLUNAS**

In [3]:
print("\nTotal de células vazias por colunas: ")
display(df.isna().sum().sort_values(ascending=False))

Total de células vazias por colunas:

quantidade         12
preco_unitario     12
id_venda            0
data                0
produto             0
forma_pagamento     0
dtype: int64

#### **VERIFICAR A QUANTIDADE DE CÉLULAS DUPLICADAS E QUAIS SÃO**

In [4]:
duplicadas_exatas = df[df.duplicated()]

print("\nTodos os registros duplicados encontrados: ")
display(duplicadas_exatas)

total_duplicadas = df.duplicated().sum()

print(f"A planilha possui {total_duplicadas} linhas duplicadas.")
print(40 * "_")

ids_repetidos = (

    df[
        df.duplicated(
            subset="id_venda",
            keep=False
        )
    ]
    .sort_values(by="id_venda")
)
print("\nVendas apenas com IDs repetidos: ")
display(ids_repetidos)

qtd_precos_dif_mesmo_id = df.groupby("id_venda")[["quantidade", "preco_unitario"]].nunique()
print("\nVerificar quantidades diferentes e preços diferentes em relaçao aos mesmos IDs:")
display(qtd_precos_dif_mesmo_id )
print("\nNão existem quantidades diferentes e preços diferentes relacionados aos mesmos IDs.")
print(80 * "_")

Todos os registros duplicados encontrados:

     id_venda        data  produto  quantidade  preco_unitario forma_pagamento
43      10633  2026-01-13   Camisa         1.0            59.9         Crédito
72      10205  2026-01-22  Mochila         4.0           129.9             Pix
124     10577  2026-02-03  Mochila         5.0           129.9          Débito
331     10265  2026-03-30  Chinelo         2.0            49.9          Débito
445     10319  2026-04-27   Camisa         7.0            59.9             Pix
504     10409  2026-05-13     Boné         7.0            39.9             Pix
644     10182  2026-06-24     Meia         3.0            19.9         Crédito
650     10862  2026-06-26    Short         1.0            79.9        Dinheiro
729     10922  2026-07-16     Boné         5.0            39.9        Dinheiro
734     10036  2026-07-18  Mochila         5.0           129.9          Débito
791     10047  2026-08-02  Jaqueta         8.0           189.9         Crédito
874     10725  2026-08-22     Meia         4.0            19.9          Débito
930     10478  2026-09-04     Boné         6.0            39.9          Débito
941     10738  2026-09-07     Boné         2.0            39.9             Pix
999     10296  2026-09-27   Camisa         8.0            59.9             Pix

A planilha possui 15 linhas duplicadas.
________________________________________

Vendas apenas com IDs repetidos:

     id_venda        data  produto  quantidade  preco_unitario forma_pagamento
734     10036  2026-07-18  Mochila         5.0           129.9          Débito
733     10036  2026-07-18  Mochila         5.0           129.9          Débito
790     10047  2026-08-02  Jaqueta         8.0           189.9         Crédito
791     10047  2026-08-02  Jaqueta         8.0           189.9         Crédito
644     10182  2026-06-24     Meia         3.0            19.9         Crédito
643     10182  2026-06-24     Meia         3.0            19.9         Crédito
71      10205  2026-01-22  Mochila         4.0           129.9             Pix
72      10205  2026-01-22  Mochila         4.0           129.9             Pix
330     10265  2026-03-30  Chinelo         2.0            49.9          Débito
331     10265  2026-03-30  Chinelo         2.0            49.9          Débito
998     10296  2026-09-27   Camisa         8.0            59.9             Pix
999     10296  2026-09-27   Camisa         8.0            59.9             Pix
444     10319  2026-04-27   Camisa         7.0            59.9             Pix
445     10319  2026-04-27   Camisa         7.0            59.9             Pix
503     10409  2026-05-13     Boné         7.0            39.9             Pix
504     10409  2026-05-13     Boné         7.0            39.9             Pix
929     10478  2026-09-04     Boné         6.0            39.9          Débito
930     10478  2026-09-04     Boné         6.0            39.9          Débito
124     10577  2026-02-03  Mochila         5.0           129.9          Débito
123     10577  2026-02-03  Mochila         5.0           129.9          Débito
42      10633  2026-01-13   Camisa         1.0            59.9         Crédito
43      10633  2026-01-13   Camisa         1.0            59.9         Crédito
873     10725  2026-08-22     Meia         4.0            19.9          Débito
874     10725  2026-08-22     Meia         4.0            19.9          Débito
940     10738  2026-09-07     Boné         2.0            39.9             Pix
941     10738  2026-09-07     Boné         2.0            39.9             Pix
650     10862  2026-06-26    Short         1.0            79.9        Dinheiro
649     10862  2026-06-26    Short         1.0            79.9        Dinheiro
728     10922  2026-07-16     Boné         5.0            39.9        Dinheiro
729     10922  2026-07-16     Boné         5.0            39.9        Dinheiro

Verificar quantidades diferentes e preços diferentes em relaçao aos mesmos IDs:

          quantidade  preco_unitario
id_venda
10001              1               1
10002              1               1
10003              1               1
10004              1               1
10005              1               1
...              ...             ...
10996              1               1
10997              1               1
10998              1               1
10999              1               1
11000              1               1

[1000 rows x 2 columns]

Não existem quantidades diferentes e preços diferentes relacionados aos mesmos IDs.
________________________________________________________________________________

#### **REMOÇÃO DAS CÉLULAS DUPLICADAS**

In [5]:
# Copia do DataFrame
df_limpo = df.copy()

# Remover Duplicadas
df_limpo = df_limpo.drop_duplicates()
print("\nLinhas originais:", len(df))
print("\nLinhas após limpeza:", len(df_limpo))

total_duplicadas_att = df_limpo.duplicated().sum()
print(f"\nAgora o número de células duplicadas no DataFrame atualizado é de: {total_duplicadas_att}.")

# Tratamento Células Vaziar
df.groupby("produto")["preco_unitario"].nunique()

Linhas originais: 1015

Linhas após limpeza: 1000

Agora o número de células duplicadas no DataFrame atualizado é de: 0.

produto
 Camisa     1
 Meia       1
 Tênis      1
Boné        1
Boné        1
CAMISA      1
CHINELO     1
Camisa      1
Chinelo     1
Chinelo     1
JAQUETA     1
Jaqueta     1
Meia        1
Mochila     1
SHORT       1
Short       1
Short       1
Tênis       1
Tênis       1
chinelo     1
jaqueta     1
Name: preco_unitario, dtype: int64

#### **PADRONIZAR A FORMATAÇÃO DE TEXTO DA COLUNA DE PRODUTOS**

In [6]:
df_limpo["produto"] = (
    
    df_limpo["produto"]
    .str.strip()
    .str.title()
)
print("\nOs produtos foram padronizado com primeira letra maiúscula e foram removidos os espaços extras.")
display(df_limpo["produto"])

print("\nQuantidade de vezes que um produto aparece na planilha:")
display(df_limpo["produto"].value_counts(dropna=False))

Os produtos foram padronizado com primeira letra maiúscula e foram removidos os espaços extras.

0        Camisa
1         Tênis
2        Camisa
3         Short
4       Chinelo
         ...
1010       Meia
1011       Meia
1012       Boné
1013      Short
1014    Chinelo
Name: produto, Length: 1000, dtype: object

Quantidade de vezes que um produto aparece na planilha:

produto
Short      140
Boné       139
Camisa     128
Meia       124
Tênis      123
Mochila    121
Chinelo    118
Jaqueta    107
Name: count, dtype: int64

#### **TRATAMENTO DAS CÉLULAS VAZIAS DA COLUNA DE PREÇO**

In [7]:
# Verificar se existe preços diferentes de um mesmo produto
preco_dif_produto = df_limpo.groupby("produto")["preco_unitario"].nunique()
display(preco_dif_produto)
print("\nA tabela atualizada não possui nenhum valor diferente de um mesmo produto.")
print(74 * "_")

# Verificar preço de cada produto
precos_produtos = df_limpo.groupby("produto")["preco_unitario"].first()
print("\nTABELA DE PREÇOS POR PRODUTO")
display(precos_produtos)

# Criar tabela de referência para preencher os preços vazios
tabela_referencia = (
    df_limpo.groupby
    ("produto")
    ["preco_unitario"]
    .transform("first")
)

# Preencher preços vazios através da tabela de referência
verificar_precos_vazios_antes = (
    df_limpo["preco_unitario"]
    .isna()
    .sum()
)

# Preencher preços vazios com a tabela de referência
df_limpo["preco_unitario"] = df_limpo["preco_unitario"].fillna(tabela_referencia)

# Verificar quantos preços continuam vazios depois da limpeza
verificar_precos_vazios_depois = (
    df_limpo["preco_unitario"]
    .isna()
    .sum()
)

# Calcular quantos preços foram preenchidos
precos_preenchidos = verificar_precos_vazios_antes - verificar_precos_vazios_depois

if verificar_precos_vazios_depois == 0:
    print("\nTodos os preços foram preenchidos com sucesso!")
    print(f"Preços preenchidos nesta execução: {precos_preenchidos}")
    print(55 * "_")
    
    print("\nTabela atualizada - ID, Produto e Preço:")
    display(df_limpo[["id_venda","produto","preco_unitario"]])

else:
    print("\nAtenção: Ainda há células vazias presentes nessa coluna")
    print(f"Preços preenchidos: {precos_preenchidos}")
    print(f"Preços ainda vazios: {verificar_precos_vazios_depois}")

produto
Boné       1
Camisa     1
Chinelo    1
Jaqueta    1
Meia       1
Mochila    1
Short      1
Tênis      1
Name: preco_unitario, dtype: int64

A tabela atualizada não possui nenhum valor diferente de um mesmo produto.
__________________________________________________________________________

TABELA DE PREÇOS POR PRODUTO

produto
Boné        39.9
Camisa      59.9
Chinelo     49.9
Jaqueta    189.9
Meia        19.9
Mochila    129.9
Short       79.9
Tênis      239.9
Name: preco_unitario, dtype: float64

Todos os preços foram preenchidos com sucesso!
Preços preenchidos nesta execução: 12
_______________________________________________________

Tabela atualizada - ID, Produto e Preço:

      id_venda  produto  preco_unitario
0        10322   Camisa            59.9
1        10088    Tênis           239.9
2        10397   Camisa            59.9
3        10414    Short            79.9
4        10033  Chinelo            49.9
...        ...      ...             ...
1010     10140     Meia            19.9
1011     10458     Meia            19.9
1012     10532     Boné            39.9
1013     10647    Short            79.9
1014     10985  Chinelo            49.9

[1000 rows x 3 columns]

#### **TRATAMENTO DAS CÉLULAS VAZIAS e QUANTIDADES NEGATIVAS DA COLUNA DE QUANTIDADE**

In [8]:
# Verificar a quantidade de células vazias
total_vendas_sem_qtd = df_limpo["quantidade"].isna().sum()
print(f"A quantidade de vendas que não possuem quantidade são: {total_vendas_sem_qtd}")
print(57 * "_")

# Identificar vendas com quantidades negativas
vendas_sem_qtd = df_limpo[
    df_limpo["quantidade"].isna()
]
print("\nCélulas que estão sem a quantidade:")
display(vendas_sem_qtd[["id_venda", "produto", "quantidade"]])

# Verificar o total de vezes que a quantidade aparece de forma negativa
total_vendas_negativas = (df_limpo["quantidade"] < 0).sum()
print(f"\nVezes que aparecem quantidades negativas na planilha: {total_vendas_negativas}")
print(55 * "_")

# Verificar quais células estão com a quantidade vazia
vendas_negativas = df_limpo[
    df_limpo["quantidade"] 
    < 0
]
print("\nCélulas que apresentam quantidade negativa:")
display(vendas_negativas)

def classificar_quantidade(quantidade):

    if pd.isna(quantidade):
        return "Ausente - REVISAR"

    elif quantidade < 0:
        return "Troca/Devolução"

    elif quantidade == 0:
        return "Zero - REVISAR"

    else:
        return "Venda Válida"

# Aplicar a função e criar coluna status para as vendas
df_limpo["status"] = df_limpo["quantidade"].apply(classificar_quantidade)

status_vazios = df_limpo["status"].isna().sum()

if status_vazios == 0:
    print("\nSUCESSO: Todos os status foram preenchidos!")
    print("Tabela atualizada - ID, Quantidade e Status")
    display(df_limpo[["id_venda", "quantidade", "status"]])

else:
    print("\nATENÇÃO: Existem status não preenchidos!")
    print(f"Quantidade de células vazias: {status_vazios}")

resumo_movimentacoes = df_limpo["status"].value_counts()
print("\n RESUMO DAS MOVIMENTAÇÕES:")
display(resumo_movimentacoes)

A quantidade de vendas que não possuem quantidade são: 12
_________________________________________________________

Células que estão sem a quantidade:

     id_venda  produto  quantidade
37      10808  Chinelo         NaN
68      10015    Tênis         NaN
178     10262  Mochila         NaN
240     10845    Short         NaN
299     10567  Mochila         NaN
339     10069   Camisa         NaN
394     10980  Jaqueta         NaN
524     10602  Jaqueta         NaN
812     10793    Tênis         NaN
841     10779    Short         NaN
922     10539    Tênis         NaN
953     10819     Boné         NaN

Vezes que aparecem quantidades negativas na planilha: 10
_______________________________________________________

Células que apresentam quantidade negativa:

     id_venda        data  produto  quantidade  preco_unitario forma_pagamento
32      10866  2026-01-11     Boné        -3.0            39.9             Pix
114     10220  2026-02-01     Boné        -1.0            39.9          Débito
316     10679  2026-03-26    Short        -3.0            79.9          Débito
333     10044  2026-03-31    Tênis        -1.0           239.9        Dinheiro
349     10557  2026-04-04  Jaqueta        -1.0           189.9             Pix
499     10590  2026-05-12  Mochila        -2.0           129.9         Crédito
560     10292  2026-05-29     Boné        -2.0            39.9         Crédito
720     10046  2026-07-15    Short        -3.0            79.9             Pix
769     10603  2026-07-28     Boné        -2.0            39.9             Pix
978     10662  2026-09-21  Jaqueta        -2.0           189.9             Pix

SUCESSO: Todos os status foram preenchidos!
Tabela atualizada - ID, Quantidade e Status

      id_venda  quantidade        status
0        10322         6.0  Venda Válida
1        10088         3.0  Venda Válida
2        10397         6.0  Venda Válida
3        10414         6.0  Venda Válida
4        10033         4.0  Venda Válida
...        ...         ...           ...
1010     10140         6.0  Venda Válida
1011     10458         1.0  Venda Válida
1012     10532         8.0  Venda Válida
1013     10647         4.0  Venda Válida
1014     10985         5.0  Venda Válida

[1000 rows x 3 columns]

 RESUMO DAS MOVIMENTAÇÕES:

status
Venda Válida         978
Ausente - REVISAR     12
Troca/Devolução       10
Name: count, dtype: int64

#### **CALCULO DO FATURAMENTO BRUTO E ANÁLISE FINANCEIRA DAS TROCAS/DEVOLUÇÕES**

In [9]:
# Criação da coluna valor total calcuando o valor total das vendas
df_limpo["valor_total"] = df_limpo["quantidade"] * df_limpo["preco_unitario"]
print("\nVALOR TOTAL DAS MOVIMENTAÇÕES")
display(df_limpo[
    ["produto", "quantidade",
     "preco_unitario", "status", "valor_total"]
])

# Gerar Faturamento Bruto
vendas_validas = df_limpo[
    df_limpo["status"] == "Venda Válida"
]

faturamento_bruto = vendas_validas["valor_total"].sum()

# Função para formatar o valor em R$
def formatar_real(valor):
    sinal = "-" if valor < 0 else ""

    numero = (
    f"{abs(valor):,.2f}"
    .replace(",", "X")
    .replace(".", ",")
    .replace("X", ".")
)
    return f"{sinal}R$ {numero}"

print(f"\nFaturamento bruto: {formatar_real(faturamento_bruto)}")
print(32 * "_")

# Gerar valor das trocas/devoluções
troca_devolucao = df_limpo[
    df_limpo["status"] == "Troca/Devolução"
]

valor_devolucoes = troca_devolucao["valor_total"].sum()
print(f"\nTrocas/Devoluções: {formatar_real(valor_devolucoes)}")

VALOR TOTAL DAS MOVIMENTAÇÕES

      produto  quantidade  preco_unitario        status  valor_total
0      Camisa         6.0            59.9  Venda Válida        359.4
1       Tênis         3.0           239.9  Venda Válida        719.7
2      Camisa         6.0            59.9  Venda Válida        359.4
3       Short         6.0            79.9  Venda Válida        479.4
4     Chinelo         4.0            49.9  Venda Válida        199.6
...       ...         ...             ...           ...          ...
1010     Meia         6.0            19.9  Venda Válida        119.4
1011     Meia         1.0            19.9  Venda Válida         19.9
1012     Boné         8.0            39.9  Venda Válida        319.2
1013    Short         4.0            79.9  Venda Válida        319.6
1014  Chinelo         5.0            49.9  Venda Válida        249.5

[1000 rows x 5 columns]

Faturamento bruto: R$ 432.044,80
________________________________

Trocas/Devoluções: -R$ 1.868,00

#### **REGISTROS QUE PRECISAM DE REVISÃO**

In [10]:
# Criar condição para células que preicsam de revisão
condicao = (
    (df_limpo["status"] == "Ausente - REVISAR") 
    | 
    (df_limpo["status"] == "Zero - REVISAR")
)
display(df_limpo[condicao])
print(f"\nQuantidade de células que precisam de revisão: {condicao.sum()}")

,id_venda,data,produto,quantidade,preco_unitario,forma_pagamento,status,valor_total
37,10808,2026-01-12,Chinelo,NaN,49.9,Débito,Ausente - REVISAR,NaN
68,10015,2026-01-22,Tênis,NaN,239.9,Pix,Ausente - REVISAR,NaN
178,10262,2026-02-16,Mochila,NaN,129.9,Crédito,Ausente - REVISAR,NaN
240,10845,2026-03-04,Short,NaN,79.9,Crédito,Ausente - REVISAR,NaN
299,10567,2026-03-21,Mochila,NaN,129.9,Crédito,Ausente - REVISAR,NaN
339,10069,2026-04-01,Camisa,NaN,59.9,Débito,Ausente - REVISAR,NaN
394,10980,2026-04-15,Jaqueta,NaN,189.9,Débito,Ausente - REVISAR,NaN
524,10602,2026-05-19,Jaqueta,NaN,189.9,Pix,Ausente - REVISAR,NaN
812,10793,2026-08-07,Tênis,NaN,239.9,Pix,Ausente - REVISAR,NaN
841,10779,2026-08-15,Short,NaN,79.9,Débito,Ausente - REVISAR,NaN
922,10539,2026-09-02,Tênis,NaN,239.9,Dinheiro,Ausente - REVISAR,NaN
953,10819,2026-09-12,Boné,NaN,39.9,Débito,Ausente - REVISAR,NaN

Quantidade de células que precisam de revisão: 12

In [11]:
# Verificar IDs duplicados após o tratamento
verf_id_tratamento = (
    df_limpo["id_venda"]
    .duplicated()
    .sum()
)

if verf_id_tratamento == 0:
    print("\nSUCESSO: Nenhum ID duplicado encontrado na base tratada.")

else:
    print(f"\nATENÇÃO: {verf_id_tratamento} ocorrências de IDs duplicados na base tratada.")

    # Identificar todos os registros com IDs repetidos
    ids_duplicados = df_limpo[
        df_limpo["id_venda"].duplicated(keep=False)
    ]

    print("\nREGISTROS COM IDs DUPLICADOS:")
    display(ids_duplicados.sort_values(by="id_venda"))

SUCESSO: Nenhum ID duplicado encontrado na base tratada.

#### **MÉTRICAS DE VENDAS: QUANTIDADES, PRODUTOS, VALORES, FORMAS DE PAGAMENTO**

In [12]:
# Contar quantos registros de vendas válidas
qtd_vendas_validas = len(vendas_validas)
print(f"\nA quantidade de registros de vendas válidas: {qtd_vendas_validas}")

# Contar quantos registros de vendas ausentes
qtd_troca_dev = len(troca_devolucao)
print(f"\nA quantidade de registros de vendas de troca/devolução: {qtd_troca_dev}")

# Contar quantos registros de vendas que precisam de revisão
qtd_pendentes = condicao.sum()
print(f"\nA quantidade de registros que precisam ser revisados: {qtd_pendentes}")

# Total de registros da planilha tratada
total_registros = len(df_limpo)
print(f"\nTotal de registros da planilha: {total_registros}")

total_classificados = (
    qtd_vendas_validas
    + qtd_troca_dev
    + qtd_pendentes
)

if total_classificados == total_registros:
    print("SUCESSO: Todos os registros foram contabilizados!")

else:
    print("ATENÇÃO: Existe uma divergência na contagem dos registros.")

# Caclular o ticket médio
ticket_médio = vendas_validas["valor_total"].mean()
print(f"\nValor do ticket médio: R$ {formatar_real(ticket_médio)}")

# Quantidade total de unidades vendidas
total_unidades = vendas_validas["quantidade"].sum()
print(f"\nTotal de unidades vendidas: {total_unidades:.0f}")

# Ranking dos produtos mais vendidos
produtos_mais_vendidos = (
    vendas_validas
    .groupby("produto")["quantidade"]
    .sum()
    .sort_values(ascending=False)
) 
print("\nQuantidade dos produtos mais vendidos:")
display(produtos_mais_vendidos)

# O produto mais vendido com a quantidade
produto_campeao = produtos_mais_vendidos.idxmax()
quantidade_campeao = produtos_mais_vendidos.max()
print(f"\nPRODUTO MAIS VENDIDO: {produto_campeao}")
print(f"QUANTIDADE VENDIDA: {quantidade_campeao:.0f} unidades")

# Produtos com maior faturamento
faturamento_produtos = (
    vendas_validas
    .groupby("produto")["valor_total"]
    .sum()
    .sort_values(ascending=False)
)
print("\nFATURAMENTO POR PRODUTO:")
display(
    faturamento_produtos
    .reset_index(name="Faturamento")
    .style.format(
        {"Faturamento": "R$ {:,.2f}"},
        decimal=",",
        thousands="."
    )
)

# O produto com maior faturamento e valor
produto_faturamento_campeao = faturamento_produtos.idxmax()
valor_faturamento_campeao = faturamento_produtos.max()
print(f"\nPRODUTO COM MAIOR FATURAMENTO: {produto_faturamento_campeao}")
print(f"VALOR DO PRODUTO COM MAIOR FATURAMENTO: {formatar_real(valor_faturamento_campeao)}")

# Quantidade e valores de cada forma de pagamento
print("\nFATURAMENTO E QUANTIDADE POR FORMAS DE PAGAMENTO:")
resumo_pagamentos = (
    vendas_validas
    .groupby("forma_pagamento", dropna=False)
    .agg(
        qtd_registros=("id_venda", "size"),
        faturamento=("valor_total", "sum")
    )
    .sort_values("faturamento", ascending=False)
)
display(
    resumo_pagamentos
    .style.format(
        {"faturamento": "R$ {:,.2f}"},
        decimal=",",
        thousands="."
    )
)

# Forma de pagamento com maior faturamento e valor
forma_pag_campeao = resumo_pagamentos["faturamento"].idxmax()
valor_forma_pag_camepao = resumo_pagamentos["faturamento"].max()
print(f"\nA FORMA DE PAGAMENTO COM MAIOR FATURAMENTO: {forma_pag_campeao}")
print(f"VALOR DA FORMA DE PAGAMENTO COM MAIOR FATURAMENTO: {formatar_real(valor_forma_pag_camepao)}")

# Faturamento por dia
datas_convertidas = pd.to_datetime(
    df_limpo["data"],
    format="%Y-%m-%d",
    errors="coerce"
)
df_limpo["data"] = datas_convertidas
vendas_validas = df_limpo[
    df_limpo["status"] == "Venda Válida"
]

faturamento_diario = (
    vendas_validas.groupby("data")["valor_total"]
    .sum()
    .sort_index()
)
print("\nFATURAMENTO DIÁRIO")
display(faturamento_diario)

A quantidade de registros de vendas válidas: 978

A quantidade de registros de vendas de troca/devolução: 10

A quantidade de registros que precisam ser revisados: 12

Total de registros da planilha: 1000
SUCESSO: Todos os registros foram contabilizados!

Valor do ticket médio: R$ R$ 441,76

Total de unidades vendidas: 4452

Quantidade dos produtos mais vendidos:

produto
Short      655.0
Boné       600.0
Camisa     582.0
Chinelo    550.0
Meia       547.0
Jaqueta    512.0
Mochila    509.0
Tênis      497.0
Name: quantidade, dtype: float64

PRODUTO MAIS VENDIDO: Short
QUANTIDADE VENDIDA: 655 unidades

FATURAMENTO POR PRODUTO:

PRODUTO COM MAIOR FATURAMENTO: Tênis
VALOR DO PRODUTO COM MAIOR FATURAMENTO: R$ 119.230,30

FATURAMENTO E QUANTIDADE POR FORMAS DE PAGAMENTO:

A FORMA DE PAGAMENTO COM MAIOR FATURAMENTO: Pix
VALOR DA FORMA DE PAGAMENTO COM MAIOR FATURAMENTO: R$ 191.405,20

FATURAMENTO DIÁRIO

data
2026-01-01     359.4
2026-01-02    1558.5
2026-01-03    1848.4
2026-01-04    1539.1
2026-01-05    2087.7
               ...
2026-09-26    3007.5
2026-09-27    2987.8
2026-09-28     249.6
2026-09-29    1687.6
2026-09-30    1027.6
Name: valor_total, Length: 266, dtype: float64

#### **MÉTRICAS DIA/MÊS**

In [13]:
# Faturamento por dia
datas_convertidas = pd.to_datetime(
    df_limpo["data"],
    format="%Y-%m-%d",
    errors="coerce"
)
df_limpo["data"] = datas_convertidas
vendas_validas = df_limpo[
    df_limpo["status"] == "Venda Válida"
]

faturamento_diario = (
    vendas_validas.groupby("data")["valor_total"]
    .sum()
    .sort_index()
)
print("\nFATURAMENTO DIÁRIO")
display(
    faturamento_diario
    .to_frame(name="Faturamento")
    .head(10)
    .style.format(
        {"Faturamento": "R$ {:,.2f}"},
        decimal=",",
        thousands=".",
        na_rep="—"
    )
)

# Faturamento por mês
faturamento_mensal = (
    vendas_validas
    .groupby(vendas_validas["data"].dt.to_period("M"))["valor_total"]
    .sum()
    .sort_index()
)
print("\nFATURAMENTO MENSAL")
display(
    faturamento_mensal
    .to_frame(name="Faturamento")
    .style.format(
        {"Faturamento": "R$ {:,.2f}"},
        decimal=",",
        thousands=".",
        na_rep="—"
    )
)

# Dia com maior faturamento
dia_campeao = faturamento_diario.idxmax()
valor_dia_campeao = faturamento_diario.max()
print(f"\nDIA DE MAIOR FATURAMENTO: {dia_campeao.strftime('%d/%m/%Y')}")
print(f"FATURAMENTO DO DIA: {formatar_real(valor_dia_campeao)}")

# Mês com maior faturamento
mes_campeao = faturamento_mensal.idxmax()
valor_mes_campeao = faturamento_mensal.max()
print(f"\nMÊS DE MAIOR FATURAMENTO: {mes_campeao}")
print(f"FATURAMENTO DO MÊS: {formatar_real(valor_mes_campeao)}")

FATURAMENTO DIÁRIO

FATURAMENTO MENSAL

DIA DE MAIOR FATURAMENTO: 01/09/2026
FATURAMENTO DO DIA: R$ 5.257,10

MÊS DE MAIOR FATURAMENTO: 2026-08
FATURAMENTO DO MÊS: R$ 58.663,70

#### **VALIDAÇÃO DOS INDICADORES**

In [14]:
total_diario = faturamento_diario.sum()
total_mensal = faturamento_mensal.sum()

# Exibir os resultados em reais
print("\nVALIDAÇÃO DOS FATURAMENTOS")

print(f"Faturamento bruto: {formatar_real(faturamento_bruto)}")
print(f"Total diário: {formatar_real(total_diario)}")
print(f"Total mensal: {formatar_real(total_mensal)}")

# Validação dos faturamentos
bruto = round(faturamento_bruto, 2)
diario = round(total_diario, 2)
mensal = round(total_mensal, 2)

if bruto == diario == mensal:
    print("\nSUCESSO: Todos os faturamentos estão consistentes!")

else:
    print("\nATENÇÃO: Divergência encontrada nos faturamentos!")
    print("Revise os seguintes resultados:")

    if bruto != diario:
        diferenca_diaria = bruto - diario

        print("\nDIVERGÊNCIA NO FATURAMENTO DIÁRIO")
        print(f"Faturamento bruto: {formatar_real(bruto)}")
        print(f"Faturamento diário: {formatar_real(diario)}")
        print(f"Diferença: {formatar_real(diferenca_diaria)}")

    if bruto != mensal:
        diferenca_mensal = bruto - mensal

        print("\nDIVERGÊNCIA NO FATURAMENTO MENSAL")
        print(f"Faturamento bruto: {formatar_real(bruto)}")
        print(f"Faturamento mensal: {formatar_real(mensal)}")
        print(f"Diferença: {formatar_real(diferenca_mensal)}")

    if diario != mensal:
        print("\nATENÇÃO: Os totais diário e mensal também são diferentes.")

    print("\nRECOMENDAÇÃO: Verifique as datas, os valores ausentes e os agrupamentos.")

VALIDAÇÃO DOS FATURAMENTOS
Faturamento bruto: R$ 432.044,80
Total diário: R$ 432.044,80
Total mensal: R$ 432.044,80

SUCESSO: Todos os faturamentos estão consistentes!

#### **RESUMO EXECUTIVO**

In [15]:
resumo_executivo = pd.DataFrame([{
    "total_registros": len(df_limpo),
    "vendas_validas": len(vendas_validas),
    "trocas_devolucoes": len(troca_devolucao),
    "pendentes_revisao": int(qtd_pendentes),

    "faturamento_bruto": faturamento_bruto,
    "valor_devolucoes": valor_devolucoes,
    "ticket_medio": vendas_validas["valor_total"].mean(),
    "unidades_vendidas": int(total_unidades),

    "produto_mais_vendido": produtos_mais_vendidos.idxmax(),
    "produto_maior_faturamento": faturamento_produtos.idxmax(),

    "pagamento_mais_utilizado": resumo_pagamentos["qtd_registros"].idxmax(),
    "pagamento_maior_faturamento": resumo_pagamentos["faturamento"].idxmax(),

    "dia_maior_faturamento": faturamento_diario.idxmax(),
    "mes_maior_faturamento": str(faturamento_mensal.idxmax())
}])


# Organizar os indicadores verticalmente
resumo_visual = resumo_executivo.T.rename(
    columns={0: "Resultado"}
)

# Identificar os indicadores financeiros
indicadores_monetarios = [
    "faturamento_bruto",
    "valor_devolucoes",
    "ticket_medio"
]

# Exibir o resumo com formatação em reais
print("\nRESUMO EXECUTIVO DO AUDITOR INTELIGENTE")

display(
    resumo_visual.style.format(
        formatar_real,
        subset=pd.IndexSlice[
            indicadores_monetarios,
            ["Resultado"]
        ]
    )
)

RESUMO EXECUTIVO DO AUDITOR INTELIGENTE

#### **EXPORTAR NO FORMATO CSV**

In [16]:
df_limpo.to_csv(
    "auditor_planilha_tratada.csv",
    index=False
)

print("Planilha tratada exportada com sucesso!")

Planilha tratada exportada com sucesso!